image: docker:latest
services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  # CONTAINER_DEV_IMAGE: dockerhub.ebi.ac.uk:4567/hdr/wes-elixir
  CONTAINER_DEV_IMAGE: ebiuk/wes-elixir
build_dev:
  stage: build
  script:

    - docker build --pull -t $CONTAINER_DEV_IMAGE .
    - docker login -u ${DOCKER_HUB_USER} -p $DOCKER_HUB_PASSWORD docker.io
    - docker push $CONTAINER_DEV_IMAGE
  only:
    - dev
  tags:
    - hdruk_docker