image: docker:stable
services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  # CONTAINER_DEV_IMAGE: dockerhub.ebi.ac.uk:4567/hdr/wes-elixir
  CONTAINER_DEV_IMAGE: ebiacuk/wes-elixir:dev-v${CI_COMMIT_TAG}
build_dev:
  stage: build
  script:

    - docker build -t $CONTAINER_DEV_IMAGE .
    - docker login -u ${DOCKER_HUB_USER} -p $DOCKER_HUB_PASSWORD docker.io
    - docker push $CONTAINER_DEV_IMAGE
  only:
    - dev
  # only:
  #   - working
  # except:
  #   - ^(?!dev).+
  tags:
    - hdruk_docker


k8s_deploy_dev:
  image: ebiacuk/wes-elixir:kubectl
  stage: deploy
  script:
    - mkdir -p ~/.kube
    - echo "$KUBE_CONF" > ~/.kube/config
    - export KUBECONFIG=~/.kube/config
    - export KUBECONFIG=~/.kube/config kubectl get nodes
    - kubectl get node
    - echo $CI_COMMIT_REF_NAME
    - kubectl -n tes set image deployment/wes-elixir-dev wes-elixir=$CONTAINER_DEV_IMAGE
    - kubectl -n tes  set image deployment/wes-celery-worker wes-celery-worker=$CONTAINER_DEV_IMAGE
    - kubectl -n tes rollout status deployment wes-celery-worker
    - kubectl -n tes rollout status deployment wes-elixir-dev 
  only:
    - dev
  # only:
  #   - working
  # except:
  #   - ^(?!dev).+
  tags:
    - hdruk_docker
