# General server settings
server:
    host: 'localhost'
    port: 7777
    debug: True

# Location of OpenAPI specs
openapi:
    path: 'openapi'
    yaml_specs: 'ga4gh.wes.0.3.0.openapi.yaml'

# Database settings
database:
    host: 'localhost'
    port: 27017
    name: wes-elixir-db

# Endpoint parameters
api_endpoints:
    default_page_size: 100
