# General server settings
server:
    host: localhost
    port: 7777
    debug: True

# WES service info settings
service_info:
    contact_info: https://github.com/elixir-europe/WES-ELIXIR
    auth_instructions_url: https://www.elixir-europe.org/services/compute/aai
    supported_file_system_protocols:
        - http
    supported_wes_versions:
        - 0.3.0
    workflow_type_versions:
        cwl:
            workflow_type_version:
                - v1.0
    workflow_engine_versions:
        cwl-tes: 0.2.0
    default_workflow_engine_parameters:
        - type: string
          default_value: "abc"
        - type: int
          default_value: "5"
    tags:
        some_param_1: something
        some_param_2: something_else
        some_param_3: another_thing

# Location of OpenAPI specs
openapi:
    path: 'openapi'
    yaml_specs: 'ga4gh.wes.0.3.0.openapi.yaml'

# Database settings
database:
    host: 'localhost'
    port: 27017
    name: wes-elixir-db

# Endpoint parameters
api_endpoints:
    default_page_size: 100
