version: '3.6'
services:

  celery-worker:
    environment:
      - WES_CONFIG="/app/wes_elixir/config/app_config.dev.yaml"

  wes-elixir:
    environment:
      - WES_CONFIG="/app/wes_elixir/config/app_config.dev.yaml"
    ports:
      - "7777:7777"

  rabbit:
    ports:
      - "5673:5672"

  mongo:
    ports:
      - "27018:27017"
