version: '3.6'
services:
  # nginx:
  #   image: nginx:latest
  #   restart: always
  #   ports:
  #     - "443:443"
  #   links:
  #     - wes-elixir
  #   volumes:
  #     - /docker/nginx/etc/ssl/:/etc/ssl/
  #     - /docker/nginx/etc/nginx/conf.d/:/etc/nginx/conf.d

  wes-elixir:
    # image: epiph-meteor:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "7777:7777"
    # expose:
    #   - "7777"
    links:
      - rabbitmq
      - mongo
    command: bash -c "cd /WES-ELIXIR/wes_elixir; python app.py & celery worker -A celery_worker -E --loglevel=info"

  mongo:
    image: mongo:4.1.3
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - /Users/gypas-adm/Documents/mongo/data/db:/data/db
