version: '3.6'
services:

  celery-worker:
    environment:
      - WES_CONFIG=/app/wes_elixir/config/app_config.prod.yaml

  wes-elixir:
    environment:
      - WES_CONFIG=/app/wes_elixir/config/app_config.prod.yaml
    ports:
      - "80:80"

  rabbit:
    ports:
      - "5672:5672"

  mongo:
    ports:
      - "27017:27017"