version: '3.6'
services:
  # nginx:
  #   image: nginx:latest
  #   restart: always
  #   ports:
  #     - "443:443"
  #   links:
  #     - wes-elixir
  #   volumes:
  #     - /docker/nginx/etc/ssl/:/etc/ssl/
  #     - /docker/nginx/etc/nginx/conf.d/:/etc/nginx/conf.d


  wes-elixir-celery:
    image: wes-elixir:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    links:
      - rabbit1
    command: bash -c "cd /WES-ELIXIR/wes_elixir; celery worker -A celery_worker -E --loglevel=info"
    volumes:
      - ./data/tests:/WES-ELIXIR/tests


  wes-elixir:
    image: wes-elixir:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "7777:7777"
    # expose:
    #   - "7777"
    links:
      - mongo
    command: bash -c "cd /WES-ELIXIR/; python wes_elixir/app.py"
    volumes:
      - ./data/tests:/WES-ELIXIR/tests

  rabbit1:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    # environment:
    #   RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
    #   RABBITMQ_DEFAULT_USER: "rabbitmq"
    #   RABBITMQ_DEFAULT_PASS: "rabbitmq"
    #   RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    links:
      - mongo

  mongo:
    image: mongo:3.2
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./data/db:/data/db
