debug_params:
    dummy_runs:
        limit: 5
        request:
            workflow_params:
                message: Hello, from Basel
            workflow_type: CWL
            workflow_type_version: v1.0
            tags:
                some_param_1: something
                some_param_2: something_else
                some_param_3: another_thing
                some_param_4: yet_another_thing
                some_param_5: and_yet_another_thing
            workflow_engine_parameters:
                some_param_1: something
                some_param_2: something_else
                some_param_3: another_thing
            workflow_url: tests/cwl/tools/echo.cwl
