# General server/service settings
server:
    host: '0.0.0.0'
    port: 80
    debug: False
    environment: production
    testing: False
    use_reloader: False

# Security settings
security:
    authorization_required: True
    jwt:
        name: "ELIXIR AAI"
        algorithm: RS256
        public_key: |-
            -----BEGIN PUBLIC KEY-----
            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyUt09EkKGW30jpggX1PY
            qrxuUw4Fo7a/uMiNvmy8CwBLfo+BgaI35Qi+ke/Dz9784CmNXjlIzNPFq+DUi+8p
            BDGAJ5hznfEoQI2TDzdiG7uIART4AEpLo9xCKrL1al37jrDmvgk98gbumnHsWKQb
            7KFRKHpIBvNVQ6v+z3nOQZ+fl1552S750ZSIfTXWXqlZohLVE9K8JwsM9i9z7h5E
            BU2cJkxPbFoZEs6zGMFEOohiAA99Nm7cW/3m3dCn+Nm5TJadEt/xR08b2GXhcg+t
            AC7qoBthpDFnUOrLbwvNWQIyE+Mch+z4+5LVTfElOGRem2tZaqYcMG/mY6EBra8p
            UwIDAQAB
            -----END PUBLIC KEY-----
        header_name: Authorization
        token_prefix: Bearer
        identity_claim: sub

# Database settings
database:
    host: 'mongo'
    port: 27017
    name: wes-elixir-db
    run_id:
        length: 6
        charset: string.ascii_uppercase + string.digits

# Storage
storage:
    permanent_dir: '/data/output'
    tmp_dir: '/data/tmp'
    remote_storage_url: 'ftp://ftp-private.ebi.ac.uk/upload/foivos'

# Celery task queuer
celery:
    broker_url: 'pyamqp://rabbit:5672//'
    result_backend: 'rpc://'
    include:
        - wes_elixir.ga4gh.wes.utils_bg_tasks
    monitor:
        timeout: 0.1
    message_maxsize: 1677721626214400

# OpenAPI specs
api:
    specs:
        - path: '20180830.74fd916da3.workflow_execution_service.swagger.yaml'
          strict_validation: True
          validate_responses: True
          swagger_ui: True
          swagger_json: True

# WES service info settings
service_info:
    contact_info: 'https://github.com/elixir-europe/WES-ELIXIR'
    auth_instructions_url: 'https://www.elixir-europe.org/services/compute/aai'
    supported_file_system_protocols:
        - http
    supported_wes_versions:
        - 0.3.0
    workflow_type_versions:
        CWL:
            workflow_type_version:
                - v1.0
    workflow_engine_versions:
        cwl-tes: 0.2.0
    default_workflow_engine_parameters:
        - type: string
          default_value: some_string
        - type: int
          default_value: '5'
    tags:
        known_tes_endpoints: 'https://tesk.c01.k8s-popup.csc.fi/'
        wes_elixir_version: 0.8.0

# Endpoint parameters
api_endpoints:
    default_page_size: 10

# TES server
tes:
    url: 'https://tes.tsi.ebi.ac.uk/'
    get_logs:
        url_root: 'v1/tasks/'
        query_params: '?view=FULL'
